### ISSUE TITLE
Exception during generation on fresh install

### ISSUE THREAD

**Issue by pavelety** [contribution-jhipster-uga/generator-jhipster-angular-material-integration#1]
Hi! 
Would like to use your generator, but can't use it with the latest versions:
- windows 10
- npm 6.12.0
- yo 3.1.0
- jhipster 6.5.0
- jhipster-angular-material-integration 1.0.17

```sh
>yo jhipster-angular-material-integration

Welcome to JHipster v6.5.0
Welcome to the JHipster angular-material-integration generator! v1.0.17

WARNING!
Your generated project used an old JHipster version (undefined)... you need at least (>=5.0.0)

events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'endsWith' of undefined
    at module.exports.getAngularAppName (C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\generator-jhipster\generators\generator-base.js:1623:56)
    at module.exports.writing (C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\generators\app\index.js:59:36)
    at Object.<anonymous> (C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\run-async\index.js:24:19
    at C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (C:\Users\Pavel\AppData\Roaming\npm\node_modules\generator-jhipster-angular-material-integration\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:433:22)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by rodolfoguinez** [comment]
Hi, @pavelety! Could you fix it?
